### PR TITLE
DOC: Fix spelling

### PR DESCRIPTION
**Pull request by ayushman17**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

- [x] Docs have been updated 

docs update => spelling: github

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### Other information:
Signed-off-by: Ayushman Singh Chauhan <ascb508@gmail.com>

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Comment by ayushman17** [comment]
Hello, can you Merge it?

**Comment by Panquesito7** [comment]
> Hello, can you Merge it?

Sorry, I can't merge PRs here, but I'll try to ping someone here or tell an Adobe maintainer. Thanks. 🙂

**Comment by Panquesito7** [comment]
@macdonst, can you review this PR, please?

**Comment by ayushman17** [comment]
Thanks!

**Pull request merged**
