### PR TITLE
Fix broken Website link

### PR DESCRIPTION
**Pull request by Pradumnasaraf**
## Description

Fix the broken website link.
Broken link - http://adobe.github.com
Updated link - https://opensource.adobe.com

## Screenshots (if appropriate):

Screenshot 2021-09-22 175729

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by Pradumnasaraf** [comment]
"I signed it"

**Comment by Pradumnasaraf** [comment]
@macdonst @Panquesito7 Please check

**Comment by macdonst** [comment]
@Pradumnasaraf I don't work for Adobe anymore so I can't help with this PR.

**Comment by Pradumnasaraf** [comment]
> @Pradumnasaraf I don't work for Adobe anymore so I can't help with this PR.

Sorry to disturb you

**Review by Panquesito7 — APPROVED** [review]

**Pull request closed without merging**
